Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - db/**/*
    - config/**/*
    - bin/**/*
    - Gemfile
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
