language: ruby
rvm:
  - 2.3.1
services:
  - elasticsearch
script:
  - bundle exec rake --trace db:create db:migrate db:test:prepare
  - RAILS_ENV=test bundle exec rspec
before_script:
  - cp config/database.yml.travis config/database.yml
